### ISSUE TITLE
linux下makefile报错

### ISSUE THREAD

**Issue by mseaspring** [wangzhione/structc#1]
1、开始是报分隔符错误，删除前面的注释不报这个错误了
2、接着报另外一个错误：
make: *** No rule to make target `main.o', needed by `structc.a'.  Stop.

貌似main.c的相对路径错了，
说明：
环境为centos 7.0

**Comment by wangzhione** [comment]
hi 
1. 下载最新的 structc 
2. 安装 jemalloc
3. gcc 使用 7+
4. make 

能不能给些更加详细的贴图. 目前手头没有 centos , 工作机都是 ubuntu

**Comment by wangzhione** [comment]
正常 structc 通过 best new gcc 编译是 0 warnning 0 error . 欢迎交流.

**Comment by mseaspring** [comment]
好的，我下载最新版本的gcc试试，谢谢老大的回复！

**Comment by mseaspring** [comment]
感谢您提供优秀的代码样例，让我受益很多，目前在学习中，生产上我改造了部分代码用上了。

**Comment by wangzhione** [comment]
争取后续继续提供更加优质可靠的 C demo 样例代码. 🙂
